### ISSUE TITLE
"Saving" is not working anymore after saving 2 or 3 times

### ISSUE THREAD

**Issue by fl164** [JackCampbell/watchX_Blocks#2]
- Working on Windows
- Starting from the example "bounce".

- "Save as" -> "bounce 2.0" in my library
- Work on the code for 10 - 20 minutes (and upload to watchX)
- Try the "Save" button on the main window, the "File"->"Save" and the "File"->"Save As" 
=> Nothing happen and the code is not saved anymore.

Check on another computer (Windows too) : same issue

Edit : export aduino code .ino is working

**Comment by mtulu-argeX** [comment]
@JackCampbell Can you please check?

**Comment by ecaldir** [comment]
This issue has been fixed with the new update of the watchX  Blocks. You can download the version 1.0.1522 from watchx.io
