### ISSUE TITLE
function "SIN" can't be used -> 'Math' was not declared in this scope

### ISSUE THREAD

**Issue by fl164** [JackCampbell/watchX_Blocks#3]
watchxsketch.ino:16:58: error: 'Math' was not declared in this scope

.........\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3\cores\arduino/Arduino.h:47:12: error: expected unqualified-id before numeric constant
#define PI 3.1415926535897932384626433832795
^
.........\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.3\cores\arduino/Arduino.h:47:12: note: in definition of macro 'PI'
#define PI 3.1415926535897932384626433832795
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Do I need to change something in a library ? or is it an issue from WatchX Blocs ?

**Comment by ecaldir** [comment]
Hi there, we are currently checking this issue. It seems like one of the libraries is not called with the "sin" block. 

It will be fixed very soon. :)
